### ISSUE TITLE
Steps tp build

### ISSUE THREAD

**Issue by MehdiChinoune** [tomasmark79/codeblocks-dark#1]
Could you show which options you uses or patches you applied to build it?

**Comment by tomasmark79** [comment]
Hello Mehdi,
of course. Here is the patch which is need to replace in the SVN Devel Branch.

[patch.zip](https://github.com/tomasmark79/codeblocks-dark/files/14529564/patch.zip)

**Comment by MehdiChinoune** [comment]
Couldn't open file.

I mean upload it to the repo.

**Comment by tomasmark79** [comment]
It is 7zip.

**Comment by MehdiChinoune** [comment]
Then why does it have `.zip` extension?

**Comment by tomasmark79** [comment]
No 7zip allowed here to upload.

**Comment by MehdiChinoune** [comment]
You call that a patch?

IIUC, Both WxWidgets and Codeblocks need changes?

**Comment by tomasmark79** [comment]
No. You call that a patch. I only have the files which I am able to change and hit the target.
